version: '3'
services:
  web:
    build: .
    ports:
     - "$PORT:8080"
    depends_on:
     - mongodb
    restart: always
    volumes:
     - ./shared/config.base.js:/home/node/app/shared/config.base.js
     - ./shared/config.env.prod.js:/home/node/app/shared/config.js
  mongodb:
    image: mongo
    restart: always
    volumes:
    - ./data:/data/db
