version: '3'
services:
  web:
    build: .
    ports:
     - "$PORT:8080"
    depends_on:
     - mongodb
    restart: always
    volumes:
     #- /workspace/openevocracy/shared/:/home/node/app/shared/
     - ./shared/:/home/node/app/shared/
     #- ./shared/config.base.js:/home/node/app/shared/config.base.js
     #- ./shared/config.env.prod.js:/home/node/app/shared/config.js
    environment:
     - ENV=prod
  mongodb:
    image: mongo
    restart: always
    volumes:
    - ./data:/data/db
